"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from . import float64

class Command(object):
    __slots__ = ["cmd", "params", "goal_meta"]

    def __init__(self):
        self.cmd = 0
        self.params = [ float64() for dim0 in range(9) ]
        self.goal_meta = ""

    def encode(self):
        buf = BytesIO()
        buf.write(Command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.cmd))
        for i0 in range(9):
            assert self.params[i0]._get_packed_fingerprint() == float64._get_packed_fingerprint()
            self.params[i0]._encode_one(buf)
        __goal_meta_encoded = self.goal_meta.encode('utf-8')
        buf.write(struct.pack('>I', len(__goal_meta_encoded)+1))
        buf.write(__goal_meta_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Command()
        self.cmd = struct.unpack(">i", buf.read(4))[0]
        self.params = []
        for i0 in range(9):
            self.params.append(float64._decode_one(buf))
        __goal_meta_len = struct.unpack('>I', buf.read(4))[0]
        self.goal_meta = buf.read(__goal_meta_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Command in parents: return 0
        newparents = parents + [Command]
        tmphash = (0x179597f6666cc70+ float64._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Command._packed_fingerprint is None:
            Command._packed_fingerprint = struct.pack(">Q", Command._get_hash_recursive([]))
        return Command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
