/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class development_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * 机器人标识（用于标记目标机器人）
     */
    public String robot_id;

    /**
     * 控制标志
     */
    public int enable_development_mode;

    /**
     * 1=开始开发模式, 0=结束开发模式
     * 所有关节的期望角度（关节顺序 : LF(hip->thigh->calf)->RF->LR->RR 12维）
     * LCM Type: float[12]
     */
    public float joint_des_q[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_q_supplement[];

    /**
     * 所有关节的期望速度
     * LCM Type: float[12]
     */
    public float joint_des_qd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_qd_supplement[];

    /**
     * 所有关节的期望扭矩
     * LCM Type: float[12]
     */
    public float joint_des_tau[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_tau_supplement[];

    /**
     * 所有关节的kp 
     * LCM Type: float[12]
     */
    public float joint_des_kp[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_kp_supplement[];

    /**
     * 所有关节的kd
     * LCM Type: float[12]
     */
    public float joint_des_kd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_kd_supplement[];

 
    public development_command_t()
    {
        joint_des_q = new float[12];
        joint_des_q_supplement = new float[4];
        joint_des_qd = new float[12];
        joint_des_qd_supplement = new float[4];
        joint_des_tau = new float[12];
        joint_des_tau_supplement = new float[4];
        joint_des_kp = new float[12];
        joint_des_kp_supplement = new float[4];
        joint_des_kd = new float[12];
        joint_des_kd_supplement = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x570c44a149669068L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.development_command_t.class))
            return 0L;
 
        classes.add(lcmtypes.development_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.robot_id.length()]; this.robot_id.getChars(0, this.robot_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.enable_development_mode); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_q[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_q_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_qd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_qd_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_tau[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_tau_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_kp[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_kp_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_kd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_kd_supplement[a]); 
        }
 
    }
 
    public development_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public development_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.development_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.development_command_t o = new lcmtypes.development_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_id = new String(__strbuf);
 
        this.enable_development_mode = ins.readInt();
 
        this.joint_des_q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_q[a] = ins.readFloat();
        }
 
        this.joint_des_q_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_q_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_qd[a] = ins.readFloat();
        }
 
        this.joint_des_qd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_qd_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_tau = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_tau[a] = ins.readFloat();
        }
 
        this.joint_des_tau_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_tau_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_kp = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_kp[a] = ins.readFloat();
        }
 
        this.joint_des_kp_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_kp_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_kd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_kd[a] = ins.readFloat();
        }
 
        this.joint_des_kd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_kd_supplement[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.development_command_t copy()
    {
        lcmtypes.development_command_t outobj = new lcmtypes.development_command_t();
        outobj.robot_id = this.robot_id;
 
        outobj.enable_development_mode = this.enable_development_mode;
 
        outobj.joint_des_q = new float[(int) 12];
        System.arraycopy(this.joint_des_q, 0, outobj.joint_des_q, 0, 12); 
        outobj.joint_des_q_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_q_supplement, 0, outobj.joint_des_q_supplement, 0, 4); 
        outobj.joint_des_qd = new float[(int) 12];
        System.arraycopy(this.joint_des_qd, 0, outobj.joint_des_qd, 0, 12); 
        outobj.joint_des_qd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_qd_supplement, 0, outobj.joint_des_qd_supplement, 0, 4); 
        outobj.joint_des_tau = new float[(int) 12];
        System.arraycopy(this.joint_des_tau, 0, outobj.joint_des_tau, 0, 12); 
        outobj.joint_des_tau_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_tau_supplement, 0, outobj.joint_des_tau_supplement, 0, 4); 
        outobj.joint_des_kp = new float[(int) 12];
        System.arraycopy(this.joint_des_kp, 0, outobj.joint_des_kp, 0, 12); 
        outobj.joint_des_kp_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_kp_supplement, 0, outobj.joint_des_kp_supplement, 0, 4); 
        outobj.joint_des_kd = new float[(int) 12];
        System.arraycopy(this.joint_des_kd, 0, outobj.joint_des_kd, 0, 12); 
        outobj.joint_des_kd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_kd_supplement, 0, outobj.joint_des_kd_supplement, 0, 4); 
        return outobj;
    }
 
}

