/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class development_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 机器人标识（用于标记机器人型号）
     */
    public String robot_id;

    /**
     * 关节状态（与quad_joint_state_t相同）
     * LCM Type: float[12]
     */
    public float joint_q[];

    /**
     * LCM Type: float[4]
     */
    public float joint_q_supplement[];

    /**
     * LCM Type: float[12]
     */
    public float joint_qd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_qd_supplement[];

    /**
     * LCM Type: float[12]
     */
    public float joint_tau[];

    /**
     * LCM Type: float[4]
     */
    public float joint_tau_supplement[];

    /**
     * IMU数据（与microstrain_lcmt相同）
     * LCM Type: float[4]
     */
    public float quat[];

    /**
     * LCM Type: float[3]
     */
    public float rpy[];

    /**
     * LCM Type: float[3]
     */
    public float omega[];

    /**
     * LCM Type: float[3]
     */
    public float acc[];

    /**
     * 遥控器指令
     * LCM Type: float[3]
     */
    public float v_des[];

    /**
     * 期望速度 [vx, vy, omega_z]
     * LCM Type: float[3]
     */
    public float omega_des[];

    /**
     * 期望角速度
     */
    public int mode;

 
    public development_state_t()
    {
        joint_q = new float[12];
        joint_q_supplement = new float[4];
        joint_qd = new float[12];
        joint_qd_supplement = new float[4];
        joint_tau = new float[12];
        joint_tau_supplement = new float[4];
        quat = new float[4];
        rpy = new float[3];
        omega = new float[3];
        acc = new float[3];
        v_des = new float[3];
        omega_des = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa6c25313663b7fa3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.development_state_t.class))
            return 0L;
 
        classes.add(lcmtypes.development_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.robot_id.length()]; this.robot_id.getChars(0, this.robot_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_q[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_q_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_qd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_qd_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_tau[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_tau_supplement[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quat[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.omega[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.acc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.omega_des[a]); 
        }
 
        outs.writeInt(this.mode); 
 
    }
 
    public development_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public development_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.development_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.development_state_t o = new lcmtypes.development_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_id = new String(__strbuf);
 
        this.joint_q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_q[a] = ins.readFloat();
        }
 
        this.joint_q_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_q_supplement[a] = ins.readFloat();
        }
 
        this.joint_qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_qd[a] = ins.readFloat();
        }
 
        this.joint_qd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_qd_supplement[a] = ins.readFloat();
        }
 
        this.joint_tau = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_tau[a] = ins.readFloat();
        }
 
        this.joint_tau_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_tau_supplement[a] = ins.readFloat();
        }
 
        this.quat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readFloat();
        }
 
        this.rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.omega = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.omega[a] = ins.readFloat();
        }
 
        this.acc = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.acc[a] = ins.readFloat();
        }
 
        this.v_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_des[a] = ins.readFloat();
        }
 
        this.omega_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.omega_des[a] = ins.readFloat();
        }
 
        this.mode = ins.readInt();
 
    }
 
    public lcmtypes.development_state_t copy()
    {
        lcmtypes.development_state_t outobj = new lcmtypes.development_state_t();
        outobj.robot_id = this.robot_id;
 
        outobj.joint_q = new float[(int) 12];
        System.arraycopy(this.joint_q, 0, outobj.joint_q, 0, 12); 
        outobj.joint_q_supplement = new float[(int) 4];
        System.arraycopy(this.joint_q_supplement, 0, outobj.joint_q_supplement, 0, 4); 
        outobj.joint_qd = new float[(int) 12];
        System.arraycopy(this.joint_qd, 0, outobj.joint_qd, 0, 12); 
        outobj.joint_qd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_qd_supplement, 0, outobj.joint_qd_supplement, 0, 4); 
        outobj.joint_tau = new float[(int) 12];
        System.arraycopy(this.joint_tau, 0, outobj.joint_tau, 0, 12); 
        outobj.joint_tau_supplement = new float[(int) 4];
        System.arraycopy(this.joint_tau_supplement, 0, outobj.joint_tau_supplement, 0, 4); 
        outobj.quat = new float[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        outobj.rpy = new float[(int) 3];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 3); 
        outobj.omega = new float[(int) 3];
        System.arraycopy(this.omega, 0, outobj.omega, 0, 3); 
        outobj.acc = new float[(int) 3];
        System.arraycopy(this.acc, 0, outobj.acc, 0, 3); 
        outobj.v_des = new float[(int) 3];
        System.arraycopy(this.v_des, 0, outobj.v_des, 0, 3); 
        outobj.omega_des = new float[(int) 3];
        System.arraycopy(this.omega_des, 0, outobj.omega_des, 0, 3); 
        outobj.mode = this.mode;
 
        return outobj;
    }
 
}

