/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class quad_joint_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * 16个主关节期望角度（关节顺序 : LF(hip->thigh->calf->wheel)->RF->LR->RR）
     * LCM Type: float[12]
     */
    public float joint_des_q[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_q_supplement[];

    /**
     * 12个主关节期望速度
     * LCM Type: float[12]
     */
    public float joint_des_qd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_qd_supplement[];

    /**
     * 12个主关节 kp
     * LCM Type: float[12]
     */
    public float joint_des_kp[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_kp_supplement[];

    /**
     * 12个主关节 kd
     * LCM Type: float[12]
     */
    public float joint_des_kd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_kd_supplement[];

    /**
     * 12个主关节期望扭矩
     * LCM Type: float[12]
     */
    public float joint_des_tau[];

    /**
     * LCM Type: float[4]
     */
    public float joint_des_tau_supplement[];

    /**
     * 电机使能标志位，一条腿一个
     * LCM Type: int32_t[4]
     */
    public int flags[];

 
    public quad_joint_command_t()
    {
        joint_des_q = new float[12];
        joint_des_q_supplement = new float[4];
        joint_des_qd = new float[12];
        joint_des_qd_supplement = new float[4];
        joint_des_kp = new float[12];
        joint_des_kp_supplement = new float[4];
        joint_des_kd = new float[12];
        joint_des_kd_supplement = new float[4];
        joint_des_tau = new float[12];
        joint_des_tau_supplement = new float[4];
        flags = new int[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1e289c59c6b88eadL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.quad_joint_command_t.class))
            return 0L;
 
        classes.add(lcmtypes.quad_joint_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_q[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_q_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_qd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_qd_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_kp[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_kp_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_kd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_kd_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_des_tau[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_des_tau_supplement[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.flags[a]); 
        }
 
    }
 
    public quad_joint_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public quad_joint_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.quad_joint_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.quad_joint_command_t o = new lcmtypes.quad_joint_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.joint_des_q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_q[a] = ins.readFloat();
        }
 
        this.joint_des_q_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_q_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_qd[a] = ins.readFloat();
        }
 
        this.joint_des_qd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_qd_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_kp = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_kp[a] = ins.readFloat();
        }
 
        this.joint_des_kp_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_kp_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_kd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_kd[a] = ins.readFloat();
        }
 
        this.joint_des_kd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_kd_supplement[a] = ins.readFloat();
        }
 
        this.joint_des_tau = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_des_tau[a] = ins.readFloat();
        }
 
        this.joint_des_tau_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_des_tau_supplement[a] = ins.readFloat();
        }
 
        this.flags = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.flags[a] = ins.readInt();
        }
 
    }
 
    public lcmtypes.quad_joint_command_t copy()
    {
        lcmtypes.quad_joint_command_t outobj = new lcmtypes.quad_joint_command_t();
        outobj.joint_des_q = new float[(int) 12];
        System.arraycopy(this.joint_des_q, 0, outobj.joint_des_q, 0, 12); 
        outobj.joint_des_q_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_q_supplement, 0, outobj.joint_des_q_supplement, 0, 4); 
        outobj.joint_des_qd = new float[(int) 12];
        System.arraycopy(this.joint_des_qd, 0, outobj.joint_des_qd, 0, 12); 
        outobj.joint_des_qd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_qd_supplement, 0, outobj.joint_des_qd_supplement, 0, 4); 
        outobj.joint_des_kp = new float[(int) 12];
        System.arraycopy(this.joint_des_kp, 0, outobj.joint_des_kp, 0, 12); 
        outobj.joint_des_kp_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_kp_supplement, 0, outobj.joint_des_kp_supplement, 0, 4); 
        outobj.joint_des_kd = new float[(int) 12];
        System.arraycopy(this.joint_des_kd, 0, outobj.joint_des_kd, 0, 12); 
        outobj.joint_des_kd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_kd_supplement, 0, outobj.joint_des_kd_supplement, 0, 4); 
        outobj.joint_des_tau = new float[(int) 12];
        System.arraycopy(this.joint_des_tau, 0, outobj.joint_des_tau, 0, 12); 
        outobj.joint_des_tau_supplement = new float[(int) 4];
        System.arraycopy(this.joint_des_tau_supplement, 0, outobj.joint_des_tau_supplement, 0, 4); 
        outobj.flags = new int[(int) 4];
        System.arraycopy(this.flags, 0, outobj.flags, 0, 4); 
        return outobj;
    }
 
}

