/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class quad_joint_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 16个主关节状态
     * LCM Type: float[12]
     */
    public float joint_q[];

    /**
     * LCM Type: float[4]
     */
    public float joint_q_supplement[];

    /**
     * LCM Type: float[12]
     */
    public float joint_qd[];

    /**
     * LCM Type: float[4]
     */
    public float joint_qd_supplement[];

    /**
     * LCM Type: int32_t[4]
     */
    public int flags[];

    public int spi_driver_status;

    /**
     * LCM Type: float[12]
     */
    public float joint_tau[];

    /**
     * LCM Type: float[4]
     */
    public float joint_tau_supplement[];

    /**
     * LCM Type: int32_t[12]
     */
    public int joint_fault[];

    /**
     * LCM Type: int32_t[4]
     */
    public int joint_fault_supplement[];

    /**
     * LCM Type: float[12]
     */
    public float joint_temp[];

    /**
     * LCM Type: float[4]
     */
    public float joint_temp_supplement[];

 
    public quad_joint_state_t()
    {
        joint_q = new float[12];
        joint_q_supplement = new float[4];
        joint_qd = new float[12];
        joint_qd_supplement = new float[4];
        flags = new int[4];
        joint_tau = new float[12];
        joint_tau_supplement = new float[4];
        joint_fault = new int[12];
        joint_fault_supplement = new int[4];
        joint_temp = new float[12];
        joint_temp_supplement = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2ec5d57b0be71f23L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.quad_joint_state_t.class))
            return 0L;
 
        classes.add(lcmtypes.quad_joint_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_q[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_q_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_qd[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_qd_supplement[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.flags[a]); 
        }
 
        outs.writeInt(this.spi_driver_status); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_tau[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_tau_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeInt(this.joint_fault[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.joint_fault_supplement[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_temp[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.joint_temp_supplement[a]); 
        }
 
    }
 
    public quad_joint_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public quad_joint_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.quad_joint_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.quad_joint_state_t o = new lcmtypes.quad_joint_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.joint_q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_q[a] = ins.readFloat();
        }
 
        this.joint_q_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_q_supplement[a] = ins.readFloat();
        }
 
        this.joint_qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_qd[a] = ins.readFloat();
        }
 
        this.joint_qd_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_qd_supplement[a] = ins.readFloat();
        }
 
        this.flags = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.flags[a] = ins.readInt();
        }
 
        this.spi_driver_status = ins.readInt();
 
        this.joint_tau = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_tau[a] = ins.readFloat();
        }
 
        this.joint_tau_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_tau_supplement[a] = ins.readFloat();
        }
 
        this.joint_fault = new int[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_fault[a] = ins.readInt();
        }
 
        this.joint_fault_supplement = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_fault_supplement[a] = ins.readInt();
        }
 
        this.joint_temp = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_temp[a] = ins.readFloat();
        }
 
        this.joint_temp_supplement = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.joint_temp_supplement[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.quad_joint_state_t copy()
    {
        lcmtypes.quad_joint_state_t outobj = new lcmtypes.quad_joint_state_t();
        outobj.joint_q = new float[(int) 12];
        System.arraycopy(this.joint_q, 0, outobj.joint_q, 0, 12); 
        outobj.joint_q_supplement = new float[(int) 4];
        System.arraycopy(this.joint_q_supplement, 0, outobj.joint_q_supplement, 0, 4); 
        outobj.joint_qd = new float[(int) 12];
        System.arraycopy(this.joint_qd, 0, outobj.joint_qd, 0, 12); 
        outobj.joint_qd_supplement = new float[(int) 4];
        System.arraycopy(this.joint_qd_supplement, 0, outobj.joint_qd_supplement, 0, 4); 
        outobj.flags = new int[(int) 4];
        System.arraycopy(this.flags, 0, outobj.flags, 0, 4); 
        outobj.spi_driver_status = this.spi_driver_status;
 
        outobj.joint_tau = new float[(int) 12];
        System.arraycopy(this.joint_tau, 0, outobj.joint_tau, 0, 12); 
        outobj.joint_tau_supplement = new float[(int) 4];
        System.arraycopy(this.joint_tau_supplement, 0, outobj.joint_tau_supplement, 0, 4); 
        outobj.joint_fault = new int[(int) 12];
        System.arraycopy(this.joint_fault, 0, outobj.joint_fault, 0, 12); 
        outobj.joint_fault_supplement = new int[(int) 4];
        System.arraycopy(this.joint_fault_supplement, 0, outobj.joint_fault_supplement, 0, 4); 
        outobj.joint_temp = new float[(int) 12];
        System.arraycopy(this.joint_temp, 0, outobj.joint_temp, 0, 12); 
        outobj.joint_temp_supplement = new float[(int) 4];
        System.arraycopy(this.joint_temp_supplement, 0, outobj.joint_temp_supplement, 0, 4); 
        return outobj;
    }
 
}

