/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class sport_client_cmd_t implements lcm.lcm.LCMEncodable
{
    public int rc_enable;

    /**
     * LCM Type: float[3]
     */
    public float velocity[];

    /**
     * LCM Type: float[3]
     */
    public float euler_angles[];

    public float body_height;

    public float step_height;

    /**
     * LCM Type: int32_t[3]
     */
    public int variable[];

    public int api;

 
    public sport_client_cmd_t()
    {
        velocity = new float[3];
        euler_angles = new float[3];
        variable = new int[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x45bce3a74c1b93c4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.sport_client_cmd_t.class))
            return 0L;
 
        classes.add(lcmtypes.sport_client_cmd_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.rc_enable); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.velocity[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.euler_angles[a]); 
        }
 
        outs.writeFloat(this.body_height); 
 
        outs.writeFloat(this.step_height); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeInt(this.variable[a]); 
        }
 
        outs.writeInt(this.api); 
 
    }
 
    public sport_client_cmd_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public sport_client_cmd_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.sport_client_cmd_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.sport_client_cmd_t o = new lcmtypes.sport_client_cmd_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.rc_enable = ins.readInt();
 
        this.velocity = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.velocity[a] = ins.readFloat();
        }
 
        this.euler_angles = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.euler_angles[a] = ins.readFloat();
        }
 
        this.body_height = ins.readFloat();
 
        this.step_height = ins.readFloat();
 
        this.variable = new int[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.variable[a] = ins.readInt();
        }
 
        this.api = ins.readInt();
 
    }
 
    public lcmtypes.sport_client_cmd_t copy()
    {
        lcmtypes.sport_client_cmd_t outobj = new lcmtypes.sport_client_cmd_t();
        outobj.rc_enable = this.rc_enable;
 
        outobj.velocity = new float[(int) 3];
        System.arraycopy(this.velocity, 0, outobj.velocity, 0, 3); 
        outobj.euler_angles = new float[(int) 3];
        System.arraycopy(this.euler_angles, 0, outobj.euler_angles, 0, 3); 
        outobj.body_height = this.body_height;
 
        outobj.step_height = this.step_height;
 
        outobj.variable = new int[(int) 3];
        System.arraycopy(this.variable, 0, outobj.variable, 0, 3); 
        outobj.api = this.api;
 
        return outobj;
    }
 
}

