"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class development_state_t(object):
    __slots__ = ["robot_id", "joint_q", "joint_q_supplement", "joint_qd", "joint_qd_supplement", "joint_tau", "joint_tau_supplement", "quat", "rpy", "omega", "acc", "v_des", "omega_des", "mode"]

    def __init__(self):
        self.robot_id = ""
        self.joint_q = [ 0.0 for dim0 in range(12) ]
        self.joint_q_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_qd = [ 0.0 for dim0 in range(12) ]
        self.joint_qd_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_tau = [ 0.0 for dim0 in range(12) ]
        self.joint_tau_supplement = [ 0.0 for dim0 in range(4) ]
        self.quat = [ 0.0 for dim0 in range(4) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.omega = [ 0.0 for dim0 in range(3) ]
        self.acc = [ 0.0 for dim0 in range(3) ]
        self.v_des = [ 0.0 for dim0 in range(3) ]
        self.omega_des = [ 0.0 for dim0 in range(3) ]
        self.mode = 0

    def encode(self):
        buf = BytesIO()
        buf.write(development_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __robot_id_encoded = self.robot_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__robot_id_encoded)+1))
        buf.write(__robot_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>12f', *self.joint_q[:12]))
        buf.write(struct.pack('>4f', *self.joint_q_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_qd[:12]))
        buf.write(struct.pack('>4f', *self.joint_qd_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_tau[:12]))
        buf.write(struct.pack('>4f', *self.joint_tau_supplement[:4]))
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack('>3f', *self.omega[:3]))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack('>3f', *self.v_des[:3]))
        buf.write(struct.pack('>3f', *self.omega_des[:3]))
        buf.write(struct.pack(">i", self.mode))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != development_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return development_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = development_state_t()
        __robot_id_len = struct.unpack('>I', buf.read(4))[0]
        self.robot_id = buf.read(__robot_id_len)[:-1].decode('utf-8', 'replace')
        self.joint_q = struct.unpack('>12f', buf.read(48))
        self.joint_q_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_qd = struct.unpack('>12f', buf.read(48))
        self.joint_qd_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_tau = struct.unpack('>12f', buf.read(48))
        self.joint_tau_supplement = struct.unpack('>4f', buf.read(16))
        self.quat = struct.unpack('>4f', buf.read(16))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.omega = struct.unpack('>3f', buf.read(12))
        self.acc = struct.unpack('>3f', buf.read(12))
        self.v_des = struct.unpack('>3f', buf.read(12))
        self.omega_des = struct.unpack('>3f', buf.read(12))
        self.mode = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if development_state_t in parents: return 0
        tmphash = (0xa6c25313663b7fa3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if development_state_t._packed_fingerprint is None:
            development_state_t._packed_fingerprint = struct.pack(">Q", development_state_t._get_hash_recursive([]))
        return development_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

