"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class quad_joint_command_t(object):
    __slots__ = ["joint_des_q", "joint_des_q_supplement", "joint_des_qd", "joint_des_qd_supplement", "joint_des_kp", "joint_des_kp_supplement", "joint_des_kd", "joint_des_kd_supplement", "joint_des_tau", "joint_des_tau_supplement", "flags"]

    def __init__(self):
        self.joint_des_q = [ 0.0 for dim0 in range(12) ]
        self.joint_des_q_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_des_qd = [ 0.0 for dim0 in range(12) ]
        self.joint_des_qd_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_des_kp = [ 0.0 for dim0 in range(12) ]
        self.joint_des_kp_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_des_kd = [ 0.0 for dim0 in range(12) ]
        self.joint_des_kd_supplement = [ 0.0 for dim0 in range(4) ]
        self.joint_des_tau = [ 0.0 for dim0 in range(12) ]
        self.joint_des_tau_supplement = [ 0.0 for dim0 in range(4) ]
        self.flags = [ 0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(quad_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.joint_des_q[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_q_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_qd[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_qd_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_kp[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_kp_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_kd[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_kd_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_tau[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_tau_supplement[:4]))
        buf.write(struct.pack('>4i', *self.flags[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != quad_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return quad_joint_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = quad_joint_command_t()
        self.joint_des_q = struct.unpack('>12f', buf.read(48))
        self.joint_des_q_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_qd = struct.unpack('>12f', buf.read(48))
        self.joint_des_qd_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_kp = struct.unpack('>12f', buf.read(48))
        self.joint_des_kp_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_kd = struct.unpack('>12f', buf.read(48))
        self.joint_des_kd_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_tau = struct.unpack('>12f', buf.read(48))
        self.joint_des_tau_supplement = struct.unpack('>4f', buf.read(16))
        self.flags = struct.unpack('>4i', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if quad_joint_command_t in parents: return 0
        tmphash = (0x1e289c59c6b88ead) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if quad_joint_command_t._packed_fingerprint is None:
            quad_joint_command_t._packed_fingerprint = struct.pack(">Q", quad_joint_command_t._get_hash_recursive([]))
        return quad_joint_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

