"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sport_client_state_t(object):
    __slots__ = ["power", "rpy", "v", "h", "state", "fault", "env"]

    def __init__(self):
        self.power = [ 0.0 for dim0 in range(2) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.v = 0.0
        self.h = 0.0
        self.state = 0
        self.fault = 0
        self.env = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(sport_client_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.power[:2]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack(">ffii", self.v, self.h, self.state, self.fault))
        buf.write(struct.pack('>3f', *self.env[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sport_client_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sport_client_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sport_client_state_t()
        self.power = struct.unpack('>2f', buf.read(8))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.v, self.h, self.state, self.fault = struct.unpack(">ffii", buf.read(16))
        self.env = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sport_client_state_t in parents: return 0
        tmphash = (0x43338a4b926ba681) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sport_client_state_t._packed_fingerprint is None:
            sport_client_state_t._packed_fingerprint = struct.pack(">Q", sport_client_state_t._get_hash_recursive([]))
        return sport_client_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

