"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sport_client_cmd_t(object):
    __slots__ = ["rc_enable", "velocity", "euler_angles", "body_height", "step_height", "variable", "api"]

    def __init__(self):
        self.rc_enable = 0
        self.velocity = [ 0.0 for dim0 in range(3) ]
        self.euler_angles = [ 0.0 for dim0 in range(3) ]
        self.body_height = 0.0
        self.step_height = 0.0
        self.variable = [ 0 for dim0 in range(3) ]
        self.api = 0

    def encode(self):
        buf = BytesIO()
        buf.write(sport_client_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.rc_enable))
        buf.write(struct.pack('>3f', *self.velocity[:3]))
        buf.write(struct.pack('>3f', *self.euler_angles[:3]))
        buf.write(struct.pack(">ff", self.body_height, self.step_height))
        buf.write(struct.pack('>3i', *self.variable[:3]))
        buf.write(struct.pack(">i", self.api))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sport_client_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sport_client_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sport_client_cmd_t()
        self.rc_enable = struct.unpack(">i", buf.read(4))[0]
        self.velocity = struct.unpack('>3f', buf.read(12))
        self.euler_angles = struct.unpack('>3f', buf.read(12))
        self.body_height, self.step_height = struct.unpack(">ff", buf.read(8))
        self.variable = struct.unpack('>3i', buf.read(12))
        self.api = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sport_client_cmd_t in parents: return 0
        tmphash = (0x45bce3a74c1b93c4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sport_client_cmd_t._packed_fingerprint is None:
            sport_client_cmd_t._packed_fingerprint = struct.pack(">Q", sport_client_cmd_t._get_hash_recursive([]))
        return sport_client_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

