"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class quad_joint_command_t(object):

    __slots__ = ["joint_des_q", "joint_des_q_supplement", "joint_des_qd", "joint_des_qd_supplement", "joint_des_kp", "joint_des_kp_supplement", "joint_des_kd", "joint_des_kd_supplement", "joint_des_tau", "joint_des_tau_supplement", "flags"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int32_t"]

    __dimensions__ = [[12], [4], [12], [4], [12], [4], [12], [4], [12], [4], [4]]

    def __init__(self):
        self.joint_des_q = [ 0.0 for dim0 in range(12) ]
        """
        16个主关节期望角度（关节顺序 : LF(hip->thigh->calf->wheel)->RF->LR->RR）
        LCM Type: float[12]
        """

        self.joint_des_q_supplement = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.joint_des_qd = [ 0.0 for dim0 in range(12) ]
        """
        12个主关节期望速度
        LCM Type: float[12]
        """

        self.joint_des_qd_supplement = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.joint_des_kp = [ 0.0 for dim0 in range(12) ]
        """
        12个主关节 kp
        LCM Type: float[12]
        """

        self.joint_des_kp_supplement = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.joint_des_kd = [ 0.0 for dim0 in range(12) ]
        """
        12个主关节 kd
        LCM Type: float[12]
        """

        self.joint_des_kd_supplement = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.joint_des_tau = [ 0.0 for dim0 in range(12) ]
        """
        12个主关节期望扭矩
        LCM Type: float[12]
        """

        self.joint_des_tau_supplement = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.flags = [ 0 for dim0 in range(4) ]
        """
        电机使能标志位，一条腿一个
        LCM Type: int32_t[4]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(quad_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.joint_des_q[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_q_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_qd[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_qd_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_kp[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_kp_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_kd[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_kd_supplement[:4]))
        buf.write(struct.pack('>12f', *self.joint_des_tau[:12]))
        buf.write(struct.pack('>4f', *self.joint_des_tau_supplement[:4]))
        buf.write(struct.pack('>4i', *self.flags[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != quad_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return quad_joint_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = quad_joint_command_t()
        self.joint_des_q = struct.unpack('>12f', buf.read(48))
        self.joint_des_q_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_qd = struct.unpack('>12f', buf.read(48))
        self.joint_des_qd_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_kp = struct.unpack('>12f', buf.read(48))
        self.joint_des_kp_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_kd = struct.unpack('>12f', buf.read(48))
        self.joint_des_kd_supplement = struct.unpack('>4f', buf.read(16))
        self.joint_des_tau = struct.unpack('>12f', buf.read(48))
        self.joint_des_tau_supplement = struct.unpack('>4f', buf.read(16))
        self.flags = struct.unpack('>4i', buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if quad_joint_command_t in parents: return 0
        tmphash = (0x1e289c59c6b88ead) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if quad_joint_command_t._packed_fingerprint is None:
            quad_joint_command_t._packed_fingerprint = struct.pack(">Q", quad_joint_command_t._get_hash_recursive([]))
        return quad_joint_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", quad_joint_command_t._get_packed_fingerprint())[0]

